config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 'users/new'
  get 'sessions/new'
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:show] do 
    get :favorites, on: :member
  end
  resources :users, only: [:new, :create, :show,:edit,:update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: '/letter_opener'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  validates :content, length: { in: 0..200 } 
  validates :content, presence: false
  belongs_to  :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites,source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: {maximum: 20}, uniqueness: true
    validates :email, presence: true, length: {maximum: 255},
      format: {with: /\A[\w.!#$%&'*+\/=?^`{|}~-]+@[\w.-]+\.[\w-]+\z/i},
      uniqueness: true
    before_validation {email.downcase!}
    has_secure_password
    validates :password, length: {minimum: 6}, allow_nil: true
    has_many :posts
    mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
      redirect_to(new_session_path) unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
   favorite = current_user.favorites.create(post_id: params[:favorite][:post_id])
   redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
   favorite = current_user.favorites.find_by(id: params[:id]).destroy
   redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, only: %i[edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end
  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        ContactMailer.anounce(@post.user).deliver
        redirect_to posts_path, notice: "写真を投稿しました!"
      else
        render :new
      end
    end
  end
  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end
  def show
    @posts = Post.where(user_id: @post.user.id).order(created_at: :desc)
  end
  def edit
  end
  def update
    if @post.update(post_params)
     redirect_to posts_path, notice: "ブログを編集しました！"
     else
    render :edit
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_path, notice:"ブログを削除しました！"
  end
  private
  def post_params
    params.require(:post).permit(:content,:image,:image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end
  def check_user
    if @current_user.nil?
     redirect_to new_session_path unless logged_in?
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     redirect_to user, notice: "ログインしました!"
    else
     flash[:danger] = "メールアドレス、パスワードが間違っています。"
     render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:danger] = "ログアウトしました!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy favorites]
  before_action :check_user, only: %i[edit update destroy]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      ContactMailer.contact_mail(@user).deliver
      redirect_to @user, notice: "アカウント作成しました!"
    else
      render :new
    end
  end
  def show
  end
  def edit
  end
  def favorites
   @post=@user.posts
   favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)
   @favorite_list= Post.find(favorites)
  end
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報を編集しました!"
    else
      render :edit
    end
  end
  def destroy
    @user.destroy
    flash[:danger] = "退会しました!"
    redirect_to new_user_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :email,
      :password, :password_confirmation, :image, :image_cache)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def check_user
    if @user.id != current_user.id
      flash[:danger] = "編集権限がありません!"
      redirect_back(fallback_location: @user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = "")
      base_title = "photo share"
      if page_title.empty?
        base_title
      else
        "#{page_title} | #{base_title}"
      end
    end
  end

app/helpers/posts_helper.rb
module PostsHelper
    def logged_in?
        current_user.present?
    end
    def choose_new_or_edit
     if action_name == 'new' || action_name == 'create'
            confirm_posts_path
     elsif action_name == 'edit'
            post_path
     end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
 def get_user_image_url(user)
    if user.image && user.image.url
       user.image.url
    else
     "fake_user.png"
    end
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>PhotoshareApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content = "width=device-width">
     <%= favicon_link_tag 'fake_user.png' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>

    
  <header class='header-menu'>
    
        <% if logged_in? %>
              <ul class='row'>

              <li class="col-md-3">
              <%= button_to posts_path, method: :get, class: "fa fa-home" do %>
              <%= fa_icon('home', type: :regular, text: "HOME") %>
              <% end %></li>
             <li class="col-sm-3">
              <%= button_to user_path(current_user.id), method: :get, class: "fa fa-user" do %>
              <%= fa_icon('user', type: :regular,text: "profile") %>
              <% end %></li>
            <li class="col-sm-4"> 
              <%= button_to session_path(current_user.id), method: :delete, class: "fa fa-sign-out" do %>
              <%= fa_icon('sign-out', type: :regular,text:'logout') %>
              <% end %>
              </li>
               <% else %>
             <li class="col-sm-2">
              <%= button_to new_user_path,:method => :get, class: "fa fa-user-plus" do %>
              <%= fa_icon('sign up', type: :regular,text: "Sign up") %>
              <% end %>
             </li>
             <li class="col-sm-3"> 
               <%= button_to new_session_path, method: :get, class: "fa fa-sign-in" do %>
              <%= fa_icon('sign in', type: :regular,text:'login') %>
              <% end %>
              </li>
             </ul>
          <% end %>
        
  </div>
   </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
 
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="post-wrapper">
  <%= form_with(model: @post, url: choose_new_or_edit, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div class="alert alert-danger alert-login">
        <h2><%= pluralize(@post.errors.count, "error", locale: :en)  %>  from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="post-form-header">
      <ul>
        <li><%= form.submit "投稿", class: "btn-original", id: "posts-btn" %></li>
      </ul>
    </div>
    <%= form.label :content, class: "sr" %>
    <%= form.text_area :content, class: "form-control", placeholder: "キャプションを入力..." %>
    <%= form.label :image, class: "sr" %>
    <%= form.file_field :image, class: "form-control", accept: "image/jpg, image/jpeg, image/png, image/gif" %>
    <%= form.hidden_field :image_cache %>
    <div class="post-image-box">
      <%= image_tag(@post.image.url, class: "form-post-image") if @post.image && @post.image.url %>
    </div>
  <% end %>
</div>

app/views/posts/confirm.html.erb
<% provide(:title, "投稿確認") %>
<div class="post-wrapper">
  <%= form_with(model: @post, local: true) do |form| %>
    <div class="post-header">
      <ul class='row'>
        <li class='col-md-3'><%= form.submit "戻る", class: "btn-original btn-green", name: "back" %></li>
        <li class='col-md-5'><span class="form-title">新規投稿を確認</span></li>
        <li class='col-md-3'><%= form.submit "投稿", class: "btn-original" %></li>
      </ul>
    </div>
    <%= form.label :content, class: "sr" %>
    <%= form.text_area :content, class: "form-control", placeholder: ".....", readonly: true %>
    <%= form.label :image, class: "sr" %>
    <%= form.hidden_field :image, class: "form-control" %>
    <%= form.hidden_field :image_cache %>
    <div class="post-image-box">
      <%= image_tag(@post.image.url, class: "form-post-image") if @post.image && @post.image.url %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% provide(:title, "")%>
<div class="posts-wrapper">
  <ul class="post-list">
   <%= link_to '新規投稿', new_post_path ,class:"picture-button" %></li>
    <% @posts.each do |post| %>
     <li class="post-list-item">
       <a href=<%= post_path(post.id)%>>
        <%= image_tag post.image.url if post.image && post.image.url %>
        </a>
    </li>
    <% end %>
  </ul>
</div>
  

app/views/posts/new.html.erb
<h2>ブログを作成する</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
  <p id="notice"><%= notice %></p>
<article class="show-post-wrapper">

    <div class="show-post-header">
      <div class="show-main">
       <div class="item-header">
       <ul class="row" style="list-style:none">
      
        <li class="col-sm-2" > <a href=<%= user_path(@post.user.id) %>>
          <%= image_tag(@post.user.image.url,class:'user-image') if @post.user.image && @post.user.image.url %></a>
        </li>
         <li class="col-sm-2">
          <%= link_to distance_of_time_in_words(Time.now, @post.created_at)+ ' ago', @post, class: 'timestamp' %>
         </li>
         <% if @post.user.id == current_user.id %>
        <li class="col-sm-3">
          <p>Posted by:  <%= link_to @post.user.name, user_path(@post.user.id) %></p>
          </li>
        
         <li class="col-sm-2">
         <% if @post.user.id == current_user.id %>
         <div> <%= link_to "編集",edit_post_path  %></div> 
         <div> <%= link_to "削除",post_path, method: :delete, data: {confirm: "本当に削除しますか?"} %></div>
         </li>
         <% end %>
          <% end %>
         </ul>
         </div>
         </div>
          <div class = "show-post-content">
           <div class="new-post-image" >     
           <%= image_tag(@post.image.url class:'show-post-image') if @post.image && @post.image.url %> 
          </div>
        </div>
       
    <div class="show-post-footer">
      <div class="favorite-wrapper">
      <% unless @post.user_id == current_user.id %>
     <% if @favorite.present? %>
      <%= button_to  favorite_path(id: @favorite.id), method: :delete, class: 'favorite-button unfavorite' do %>
      <%= fa_icon('thumbs-up', type: :regular, text: "favorite") %>
    <% end %>
    <% else %>
      <%= button_to  favorites_path(favorite: {post_id: @post.id} ), method: :post, class: "favorite-button" do %>
      <%= fa_icon('thumbs-up', type: :solid, text: "favorite") %>
    <% end %>
    <% end %>
       <%= link_to "HOME", posts_path %>
   <% end %>
  </div>
 </div>
</div>
</article>



app/views/users/_form.html.erb
<div class="login-form-wrapper">
  <div class="login-form-header">
    <h1 class="login-form-title">photo_shares</h1>
  </div>
  <%= form_with(model: user, local: true, class: "login-form") do |form| %>
    <%= render partial: "error_messages", locals: {user: user} %>
    <h2 class="login-form-subtitle">登録して友達の写真や動画をチェックしよう</h2>
    <%= image_tag(user.image.url, class: "form-user-image") if user.image && user.image.url %>
    <%= form.label :email, class: "sri" %>
    <%= form.email_field :email, class: "form-control", placeholder: t("views.users.email"), required: true, autofocus: true %>
    <%= form.text_field :name, class: "form-control", placeholder: t("views.users.name"), required: true %>
    <%= form.label :image, class: "sri" %>
    <%= form.file_field :image, class: "form-control", accept: "image/jpg, image/jpeg, image/png, image/gif" %>
    <%= form.hidden_field :image_cache %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password, class: "form-control", placeholder: t("views.users.password"), required: true, minlength: 6 %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: t("views.users.password_confirmation"), required: true %>
    <%= form.submit "登録する", class: "btn-primary", id: "active-btn" %>
    <p class="explanation-rule">登録することで、本規約、データに関するポリシーに同意するものとします。</p>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "プロファイルを編集") %>
<div class="user-edit-box">
  <ul class="user-edit-form row">
    <li class='col-md-3'><p>プロフィールを編集</p> </li>
    <li class='col-md-3'>
      <%= link_to "logout", session_path(current_user.id), class: "user-edit-block", method: :delete %>
    </li>
    <li class='col-md-3'>
      <%= link_to "退会", user_path(current_user.id), class: "user-edit-block", method: :delete, data: {confirm: "本当に退会してよろしいでしょうか?"} %>
    </li>
  </ul>
<article class="user-edit-wrapper">
<%= form_with(model: @user,url: user_path, local: true, class: "edit_form") do |form| %>
   <% if @user.errors.any? %>
    <div class="alert alert-danger alert-login">
     <h3><%= pluralize(@user.errors.count, "error", locale: :en)  %> prohibited this <%= @user.name %> from being saved:</h3>
     <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
       <% end %>
    </ul>
   </div>
   <% end %>
    <table class="edit-user">
    <ul>
      <li>
        <%= image_tag(get_user_image_url(@user), class: "user-image") %>
         <%= @user.name %></td>
      </li>
      <li><%= form.label :name %>
       <%= form.text_field :name, class: "form-control", placeholder: t("views.users.name"), required: true %> </li>

       <li><%= form.label :email %></li>
       <li><%= form.email_field :email, class: "form-control", placeholder: t("views.users.email"), required: true %></li>

       <li><%= form.label :image %></li>
       <li><%= form.file_field :image, class: "form-control", accept: "image/jpg, image/jpeg, image/png, image/gif" %></li>
     </ul>
     </table>
     <tr>
      <th>現在のプロフィール写真</th>
      <td>
        <%= form.hidden_field :image_cache %>
        <% if @user.image && @user.image.url %>
          <%= image_tag(@user.image.url, class: "form-user-image") %>
        <% else %>
        
        <% end %>
      </td>
     </tr>
    <tr>
      <th></th>
      <td><%= form.submit "変更", class: "btn btn-primary" %></td>
    </tr>
  </table>
 <% end %>
</article>
</div>

app/views/users/favorites.html.erb
<% provide(:title, "(@#{current_user.name})")%>
<div class="user-show-wrapper">
<h2><%= current_user.name %>のお気に入り一覧</h2>
  <% if @user.id == current_user.id %>
    <div class="user-show-edit">
        <%= image_tag(get_user_image_url(@user),class:'user-image') %>
        <li><%= link_to "プロフィールを編集",edit_user_path(@user) %></li>
        </div>
      <% end %>
 <div class="show-nav">
  <ul>
    <li class="show-nav-list" id="posts">
     <%= link_to "ブログを新規作成", posts_path %>
    </li>

  </ul>
</div>  
</div>
<ul>

<% if @favorite_list.present? %>
  <% @favorite_list.each do |favorite| %>
    <%= favorite.user.name %>
    <%= image_tag favorite.image.url %> 
    <% end %>
  
<% end %>
</ul>

app/views/users/index.html.erb
<div class="registrations-new">
  <div class="login-form-header">
    <h1 class="login-form-title">photo_share</h1>
  </div>
  <%= form_with(model: user, local: true, class: "login-form") do |form| %>
      <% if user.errors.any? %>
    <div class="alert alert-danger alert-login">
     <h3><%= pluralize(user.errors.count, "error", locale: :en)  %> prohibited this <%= user.name %> from being saved:</h3>
     <ul>
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
       <% end %>
    </ul>
   </div>
   <% end %>
    <h2>登録した写真や動画をチェック</h2>
    <%= image_tag(user.image.url, class: "form-user-image") if user.image && user.image.url %>
    <%= form.label :email, class: "sri" %>
    <%= form.email_field :email, class: "form-control", placeholder: t("views.users.email"), required: true, autofocus: true %>
    <%= form.label :name, class: "sri" %>
    <%= form.text_field :name, class: "form-control", placeholder: t("views.users.name"), required: true %>
    <%= form.label :image, class: "sri" %>
    <%= form.file_field :image, class: "form-control", accept: "image/jpg, image/jpeg, image/png, image/gif" %>
    <%= form.hidden_field :image_cache %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password, class: "form-control", placeholder: t("views.users.password"), required: true, minlength: 6 %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: t("views.users.password_confirmation"), required: true %>
    <%= form.submit "登録する", class: "btn-primary", id: "active-btn" %>
  <% end %>
</div>

app/views/users/new.html.erb

<% provide(:title, "ログイン") %>

  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-login">
     <h3><%= pluralize(@user.errors.count, "error", locale: :en)  %> prohibited this <%= @user.name %> from being saved:</h3>
     <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg%></li>
       <% end %>
    </ul>
   </div>
   <% end %>
    <%= form_with(model: @user, local: true, class: "login-form") do |form| %>
    <h1>Sign up</h1>
    <%= image_tag(@user.image.url, class: "user-image") if @user.image && @user.image.url %>

    <%= form.label :name, class: "sri" %>
    <%= form.text_field :name, class: "form-control", placeholder: 'your name', required: true %>
    <%= form.label :email, class: "sri" %>
   <%= form.email_field :email, class: "form-control", placeholder: 'your email', required: true, autofocus: true %>
     <%= form.label :image, class: "sri" %>
    <%= form.file_field :image, class: "form-control", accept: "image/jpg, image/jpeg, image/png, image/gif" %>
    <%= form.hidden_field :image_cache %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password, class: "form-control", placeholder: 'your password', required: true, minlength: 6 %>
    <%= form.label :password, class: "sri" %>
    <%= form.password_field :password_confirmation, class: "form-controle", placeholder: 'your password confirmation', required: true %>
    <%= form.submit "登録する", class: "btn-primary", id: "active-btn" %>
     <p><%=link_to "ログインする", new_session_path %></p>
  <% end %>
  <div class="enter-login-wrapper">
 
</div>
</div>





app/views/users/show.html.erb
<% provide(:title, "(@#{@user.name})") %>
<div class="user-show-wrapper">

<h2><%= @user.name %>のプロファイル</h2>
   <h1><%= @user.name %></h1>
      <% if @user.id == current_user.id %>
        <div class="user-show-edit">
        <%= image_tag(get_user_image_url(@user),class:'user-image') %>
        </div>
      <% end %>
 <div class="show-nav">
  <ul>
    <li class="show-nav-list" id="posts">
     <%= link_to "ブログを新規作成", posts_path %>
    </li>
    <li>投稿 <span><%= @user.posts ? @user.posts.count : 0%></span>件</li>
      <% if @user.id == current_user.id %>
     <li><%= link_to "プロフィールを編集",edit_user_path(@user) %></li>
     <% end %>
    
   
      <li class="favorite-list" id="favorites">
      <%= link_to " お気に入り一覧",favorites_user_path(@user.id) %>
    </li>
    </li>
  </ul>

</div>  

<p>メールアドレス: <%= @user.email %></p>
</div>
<%# <% count = 0 %> %>
<%# <% @login_user_posts.each do |post| %>
<%# <% count += post.favorites.count if  %>
<%# post.favorites.present? %> %>
<%# <% end %> %>
<%# <p>お気に入りされた合計数: <%= count %></p> %> %>

<% if @favorite_list.present? %>
  <% @favorite_list.each do |post| %>
    <%= @post.user.name %>
    <%= image_tag(@post.image.url class:'show-post-image') if @post.image && @post.image.url %> 
    <% end %>
<% end %>